# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gpio_demo_pb2 as gpio__demo__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gpio_demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GpioDemoStub(object):
    """======================= Service =======================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PressButton = channel.unary_unary(
                '/simgpio.GpioDemo/PressButton',
                request_serializer=gpio__demo__pb2.ButtonReq.SerializeToString,
                response_deserializer=gpio__demo__pb2.SimpleReply.FromString,
                _registered_method=True)
        self.ReleaseButton = channel.unary_unary(
                '/simgpio.GpioDemo/ReleaseButton',
                request_serializer=gpio__demo__pb2.ButtonReq.SerializeToString,
                response_deserializer=gpio__demo__pb2.SimpleReply.FromString,
                _registered_method=True)
        self.GetLedState = channel.unary_unary(
                '/simgpio.GpioDemo/GetLedState',
                request_serializer=gpio__demo__pb2.Empty.SerializeToString,
                response_deserializer=gpio__demo__pb2.LedState.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/simgpio.GpioDemo/Reset',
                request_serializer=gpio__demo__pb2.Empty.SerializeToString,
                response_deserializer=gpio__demo__pb2.SimpleReply.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/simgpio.GpioDemo/Configure',
                request_serializer=gpio__demo__pb2.ConfigureReq.SerializeToString,
                response_deserializer=gpio__demo__pb2.SimpleReply.FromString,
                _registered_method=True)
        self.EventStream = channel.unary_stream(
                '/simgpio.GpioDemo/EventStream',
                request_serializer=gpio__demo__pb2.Empty.SerializeToString,
                response_deserializer=gpio__demo__pb2.LedState.FromString,
                _registered_method=True)


class GpioDemoServicer(object):
    """======================= Service =======================
    """

    def PressButton(self, request, context):
        """==== RPC cũ (giữ nguyên chữ ký để tương thích), nhưng SimpleReply nay có thêm status ====
        Nhấn nút (giả lập): index ∈ {0,1}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseButton(self, request, context):
        """Nhả nút (giả lập): index ∈ {0,1}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLedState(self, request, context):
        """Lấy trạng thái LED hiện tại (không thay đổi mô phỏng).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """==== RPC mới (tuỳ chọn, tiện cho demo/CI) ====
        Đưa mô phỏng về trạng thái ban đầu (tắt led, nhả nút, reset counter...).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Cấu hình mô phỏng: số lượng LED, active low, giá trị khởi tạo...
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request, context):
        """(Tuỳ chọn) Stream trạng thái LED về client mỗi khi có thay đổi.
        Thích hợp cho UI realtime; server có thể push sau Press/Release/Reset/Configure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GpioDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PressButton': grpc.unary_unary_rpc_method_handler(
                    servicer.PressButton,
                    request_deserializer=gpio__demo__pb2.ButtonReq.FromString,
                    response_serializer=gpio__demo__pb2.SimpleReply.SerializeToString,
            ),
            'ReleaseButton': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseButton,
                    request_deserializer=gpio__demo__pb2.ButtonReq.FromString,
                    response_serializer=gpio__demo__pb2.SimpleReply.SerializeToString,
            ),
            'GetLedState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLedState,
                    request_deserializer=gpio__demo__pb2.Empty.FromString,
                    response_serializer=gpio__demo__pb2.LedState.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=gpio__demo__pb2.Empty.FromString,
                    response_serializer=gpio__demo__pb2.SimpleReply.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=gpio__demo__pb2.ConfigureReq.FromString,
                    response_serializer=gpio__demo__pb2.SimpleReply.SerializeToString,
            ),
            'EventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=gpio__demo__pb2.Empty.FromString,
                    response_serializer=gpio__demo__pb2.LedState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simgpio.GpioDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simgpio.GpioDemo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GpioDemo(object):
    """======================= Service =======================
    """

    @staticmethod
    def PressButton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simgpio.GpioDemo/PressButton',
            gpio__demo__pb2.ButtonReq.SerializeToString,
            gpio__demo__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseButton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simgpio.GpioDemo/ReleaseButton',
            gpio__demo__pb2.ButtonReq.SerializeToString,
            gpio__demo__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLedState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simgpio.GpioDemo/GetLedState',
            gpio__demo__pb2.Empty.SerializeToString,
            gpio__demo__pb2.LedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simgpio.GpioDemo/Reset',
            gpio__demo__pb2.Empty.SerializeToString,
            gpio__demo__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simgpio.GpioDemo/Configure',
            gpio__demo__pb2.ConfigureReq.SerializeToString,
            gpio__demo__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/simgpio.GpioDemo/EventStream',
            gpio__demo__pb2.Empty.SerializeToString,
            gpio__demo__pb2.LedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
