# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpio_demo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gpio_demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgpio_demo.proto\x12\x07simgpio\"\x07\n\x05\x45mpty\"\x1a\n\tButtonReq\x12\r\n\x05index\x18\x01 \x01(\x05\"f\n\x0c\x43onfigureReq\x12\x11\n\tled_count\x18\x01 \x01(\x05\x12\x17\n\x0fleds_active_low\x18\x02 \x01(\x08\x12\x15\n\rinitial_value\x18\x03 \x01(\x05\x12\x13\n\x0breset_after\x18\x04 \x01(\x08\"\x18\n\x08LedState\x12\x0c\n\x04leds\x18\x01 \x03(\x05\";\n\x0bSimpleReply\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x1f\n\x06status\x18\x02 \x01(\x0e\x32\x0f.simgpio.Status*B\n\x06Status\x12\r\n\tSTATUS_OK\x10\x00\x12\x16\n\x12STATUS_INVALID_ARG\x10\x01\x12\x11\n\rSTATUS_FAILED\x10\x02\x32\xcd\x02\n\x08GpioDemo\x12\x37\n\x0bPressButton\x12\x12.simgpio.ButtonReq\x1a\x14.simgpio.SimpleReply\x12\x39\n\rReleaseButton\x12\x12.simgpio.ButtonReq\x1a\x14.simgpio.SimpleReply\x12\x30\n\x0bGetLedState\x12\x0e.simgpio.Empty\x1a\x11.simgpio.LedState\x12-\n\x05Reset\x12\x0e.simgpio.Empty\x1a\x14.simgpio.SimpleReply\x12\x38\n\tConfigure\x12\x15.simgpio.ConfigureReq\x1a\x14.simgpio.SimpleReply\x12\x32\n\x0b\x45ventStream\x12\x0e.simgpio.Empty\x1a\x11.simgpio.LedState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpio_demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=256
  _globals['_STATUS']._serialized_end=322
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_BUTTONREQ']._serialized_start=37
  _globals['_BUTTONREQ']._serialized_end=63
  _globals['_CONFIGUREREQ']._serialized_start=65
  _globals['_CONFIGUREREQ']._serialized_end=167
  _globals['_LEDSTATE']._serialized_start=169
  _globals['_LEDSTATE']._serialized_end=193
  _globals['_SIMPLEREPLY']._serialized_start=195
  _globals['_SIMPLEREPLY']._serialized_end=254
  _globals['_GPIODEMO']._serialized_start=325
  _globals['_GPIODEMO']._serialized_end=658
# @@protoc_insertion_point(module_scope)
